bgrm: sanity check arguments

diff --git a/bin/bgrm b/bin/bgrm
--- a/bin/bgrm
+++ b/bin/bgrm
@@ -4,8 +4,13 @@
 #	- Cameron Simpson <cs@cskk.id.au> 19jul1998
 #
 
+set -ue
+
+cmd=$0
+usage="Usage: $cmd [rm-opts...] paths"
+
 rmopts=
-while :
+while [ $# -gt 0 ]
 do
   case $1 in
     --) shift; break ;;
@@ -14,6 +19,22 @@ do
   esac
   shift
 done
+
+if [ $# = 0 ]
+then
+  echo "$cmd: missing paths" >&2
+  badopts=1
+else
+  for arg
+  do
+    [ -e "$arg" ] || {
+      echo "$cmd: missing path: $arg" >&2
+      badopts=1
+    }
+  done
+fi
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 xit=0
 
