execif: add diff mode

diff --git a/bin/execif b/bin/execif
--- a/bin/execif
+++ b/bin/execif
@@ -4,17 +4,55 @@
 #	- Cameron Simpson <cs@zip.com.au> 23jun1998
 #
 
+set -ue
+
 : ${TMPDIR:=/tmp}
 
-cmd=$0
-usage="Usage: $cmd command [args...]"
+diff_mode=
+diff_file=
 
-[ $# = 0 ] && { echo "$usage" >&2; exit 2; }
+cmd=$0
+usage="Usage: $cmd [{-u|-c} diff_file] command [args...]"
+
+badopts=
+
+while [ $# -gt 0 ]
+do
+  case "$1" in
+    -u|-c)      diff_mode=$1
+                diff_file=$2
+                shift
+                ;;
+    --)         shift; break ;;
+    -?*)        echo "$cmd: unrecognised option: $1" >&2
+                badopts=1
+                ;;
+    *)          break ;;
+  esac
+  shift
+done
+
+if [ $# = 0 ]
+then
+  echo "$cmd: missing command" >&2
+  badopts=1
+fi
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 tmp=$TMPDIR/execif.$$
-trap 'rm -f "$tmp"' 0
-trap 'rm -f "$tmp"; exit 1' 1 2 13 15
+new=$tmp.new
+out=$tmp.out
+trap 'rm -f "$new" "$out"' 0
+trap 'rm -f "$new" "$out"; exit 1' 1 2 13 15
 
-stripwhite >"$tmp" || exit 1
-[ -s "$tmp" ] || exit 0
-"$@" <"$tmp"
+if [ -n "$diff_mode" ]
+then
+  [ -f "$diff_file" ] || >>"$diff_file"
+  tee "$new" | diff "$diff_mode" -b "$diff_file" - >"$out" \
+  || cat "$new" >"$diff_file"
+else
+  stripwhite >"$out"
+fi
+[ -s "$out" ] || exit 0
+"$@" <"$out"
