fixexts: fall back to the MIME subtype as the file extension if nothing is found in te mime.types files

diff --git a/bin/fixexts b/bin/fixexts
--- a/bin/fixexts
+++ b/bin/fixexts
@@ -35,15 +35,15 @@ do
                                continue
                              }
   fi
-
-  prefext=`mime-ext "$type"` || { echo "$cmd: cannot look up preferred extension for $type" >&2
-                                 xit=1
-                                 continue
-                               }
-  [ -n "$prefext" ] || { echo "$cmd: no preferred extension for $type" >&2
-                         xit=1
-                         continue
-                       }
+  prefext=`mime-ext "$type"` || {
+    echo "$cmd: cannot look up preferred extension for $type" >&2
+    xit=1
+    continue
+  }
+  [ -n "$prefext" ] || {
+    # use the subtype from the mime type
+    prefext=$( expr "x$type" : 'x.*/\([^/][^/]*\)' )
+  }
 
   # see if ext is ok already
   fbase=`basename "$f"`
