get-mailman-archive: recode using pilfer

diff --git a/bin/get-mailman-archive b/bin/get-mailman-archive
--- a/bin/get-mailman-archive
+++ b/bin/get-mailman-archive
@@ -1,8 +1,12 @@
-#!/bin/sh -ue
+#!/bin/sh
 #
 # Download mailman archive into a UNIX mbox file.
 #       - Cameron Simpson <cs@zip.com.au> 19jan2009
 #
+
+set -ue
+
+: ${TMPDIR:=/tmp}
 
 cmd=`basename "$0"`
 usage="Usage: $cmd archive-page-url... >mlist.mbox"
@@ -29,17 +33,33 @@ fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
+tmpf=$TMPDIR/$cmd.$$
+trap 'rm -f "$tmpf"' 0
+trap 'rm -f "$tmpf"; exit 1' 1 3 15
+
 for url
 do
-  pageurls "$url" \
-  | egrep '\.(txt|gz)$' \
-  | while read url
+  # these are easy
+  pilfer url "$url" hrefs .txt save:-
+
+  # some sites hand out .txt.gz decompressed! ouch!
+  pilfer url "$url" hrefs .txt.gz \
+  | while read -r url
     do
-      case "$url" in
-        *.gz) $trace wget -O - "$url" | gunzip ;;
-        *.txt) $trace wget -O - "$url" ;;
-        *) echo "$cmd: skipping unexpected URL: $url" >&2 ;;
-      esac
+      if pilfer url "$url" save:- >"$tmpf"
+      then
+        case `file "$tmpf"` in
+          # expected
+          *compressed\ data*)
+            gunzip < "$tmpf"
+            ;;
+          # surprise!
+          *)cat <"$tmpf"
+            ;;
+        esac
+      else
+        echo "$cmd: warning: failed fetch: $url" >&2
+      fi
     done
 done \
 | fix-mail-dates --mbox \
