hgbox: support multiple hgboxen

diff --git a/bin/hgbox b/bin/hgbox
--- a/bin/hgbox
+++ b/bin/hgbox
@@ -14,29 +14,45 @@
 
 set -ue
 
-: ${HGBOX_MASTER:=ssh://home/var/hgbox}
-: ${HGBOX_LOCAL:=$HOME/var/hgbox}
+: ${HGBOX:=$HOME/var/hgbox}
+
+hgmasterbase=ssh://home/var/hgbox-MASTER
+hglocalbase=$HGBOX
 
 cmd=`basename "$0"`
 usage="Usage:
-  $cmd [-L local] [-R master] export [-f]
-  $cmd [-L local] [-R master] sync [-q]"
+  $cmd [options...] add sets...
+    Add named sets from master to local sets.
+  $cmd [options...] export [-f] [sets...]
+    Export files from the named sets. Destructively undoes local changes.
+    -f: Force export instead of asking.
+  $cmd [options...] init sets...
+    Initialise new sets, both locally and at the master.
+  $cmd [options...] sync [-q] [sets...]
+    Sync local sets. Update master unless -q (quick).
+ Options:
+  -L local      Specify local base. Default from \$HGBOX: $hglocalbase
+  -R remote     Specify remote master base. Default: $hgmasterbase
+  -n            No action. Recite actions.
+  -q            Quiet.
+  -v            Verbose.
+  -x            Trace execution of actions."
 
-hgmaster=$HGBOX_MASTER
-hglocal=$HGBOX_LOCAL
 rsopts=-ptgolH
-trace=  ##set-x
+trace= ##set-x
 verbose=
 silent=
+xopt=
 
 badopts=
 
 while [ $# -gt 0 ]
 do
   case $1 in
-    -L) hglocal=$2; shift ;;
+    -L) hglocalbase=$2; shift ;;
     -R) hgmaster=$2; shift ;;
-    -x) trace=set-x ;;
+    -n) trace=eecho ;;
+    -x) trace=set-x xopt=-x;;
     -v) silent= verbose=1 ;;
     -q) silent=1 verbose= ;;
     --) shift; break ;;
@@ -56,6 +72,11 @@ else
   op=$1
   shift
   case "$op" in
+    add)
+        [ $# -gt 0 ] || { echo "$cmd: $op: missing sets" >&2
+                          badopts
+                        }
+        ;;
     export)
         force_export=
         if [ $# -gt 0 ] && [ "x$1" = x-f ]
@@ -63,9 +84,12 @@ else
           shift
           force_export=1
         fi
-        [ $# = 0 ] || { echo "$cmd: extra arguments after $op: $*" >&2
-                        badopts=1
-                      }
+        [ $# -gt 0 ] || set -- `cd "$hglocalbase"; echo [a-z]*`
+        ;;
+    init)
+        [ $# -gt 0 ] || { echo "$cmd: $op: missing sets" >&2
+                          badopts
+                        }
         ;;
     sync)
         sync_quick=
@@ -74,9 +98,7 @@ else
           shift
           sync_quick=1
         fi
-        [ $# = 0 ] || { echo "$cmd: extra arguments after $op: $*" >&2
-                        badopts=1
-                      }
+        [ $# -gt 0 ] || set -- `cd "$hglocalbase"; echo [a-z]*`
         ;;
     *)  echo "$cmd: unsupported op: $op" >&2
         badopts=1
@@ -87,6 +109,7 @@ fi
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 hg="$trace hg"
+inhg="$trace inhg $xopt"
 
 sync_in()
 {
@@ -113,7 +136,7 @@ sync_in()
           ;;
     esac
   done
-  [ $silent ] || echo "import from $sync_in_outside"
+  [ $silent ] || echo "$set: import from $sync_in_outside"
   $trace rsync -r --delete $rsopts "$@" "$sync_in_outside/" "$sync_in_inside/" >&2
 }
 
@@ -143,7 +166,7 @@ sync_out()
           ;;
     esac
   done
-  [ $silent ] || echo "export to $sync_out_outside"
+  [ $silent ] || echo "$set: export to $sync_out_outside"
   $trace rsync -r --delete $rsopts "$@" "$sync_out_inside/" "$sync_out_outside/" >&2
 }
 
@@ -184,39 +207,61 @@ withhgoutmap()
   [ $ok ] || { echo "$cmd: ABORTING" >&2; return 1; }
 }
 
-cd "$hglocal" || exit 1
+xit=0
 
-case "$op" in
-  export)
-    if [ $force_export ] \
-    || { [ -t 0 ] && ask "really export from hgbox to exterior directories"; }
-    then
-      withhgoutmap sync_out
-    else
-      echo "$cmd: aborting export" >&2
-      exit 1
-    fi
-    ;;
-  sync)
+for set
+do
+  hgbox=$hglocalbase/$set
+  rhgbox=$hgmasterbase/$set
 
-    withhgoutmap sync_in
+  ( set -ue
+    case "$op" in
+      add)
+        $hg clone "$rhgbox" "$hgbox"
+        ;;
 
-    hgstat=`$hg stat`
-    if [ -n "$hgstat" ]
-    then
-      $hg addremove
-      $hg commit -m "sync in `hostname`:`pwd` `date +'%Y-%m-%d-%H:%M:%S'`"
-    fi
+      export)
+        cd "$hgbox" || exit 1
+        if [ $force_export ] \
+        || { [ -t 0 ] && ask "really export from $hgbox to exterior directories"; }
+        then
+          withhgoutmap sync_out
+        else
+          echo "$cmd: $op: $hgbox: aborting" >&2
+          exit 1
+        fi
+        ;;
 
-    if not [ $sync_quick ]
-    then
-      [ $silent ] || echo "import from $hgmaster"
-      $hg fetch "$hgmaster"
-      withhgoutmap sync_out
+      init)
+        $inhg --init "$rhgbox"
+        $hg clone "$rhgbox" "$hgbox"
+        ;;
 
-      [ $silent ] || echo "export to $hgmaster"
-      $hg push "$hgmaster"
-      inhg "$hgmaster" $hg up
-    fi
-    ;;
-esac
+      sync)
+        cd "$hgbox" || exit 1
+
+        withhgoutmap sync_in
+
+        hgstat=`$hg stat`
+        if [ -n "$hgstat" ]
+        then
+          $hg addremove
+          $hg commit -m "sync in `hostname`:`pwd` `date +'%Y-%m-%d-%H:%M:%S'`"
+        fi
+
+        if not [ $sync_quick ]
+        then
+          [ $silent ] || echo "$set: import from $rhgbox"
+          $hg fetch "$rhgbox"
+          withhgoutmap sync_out
+
+          [ $silent ] || echo "$set: export to $rhgbox"
+          $hg push "$rhgbox"
+          $inhg "$rhgbox" $hg up
+        fi
+        ;;
+    esac
+  ) || xit=1
+done
+
+exit $xit
