histbackup: mklinktree: implement using rsync --link-dest instead of cp -ral

diff --git a/bin/histbackup b/bin/histbackup
--- a/bin/histbackup
+++ b/bin/histbackup
@@ -481,27 +481,31 @@ then
       $trace cp -ra --reflink "$_mkl_src" "$_mkl_dst"
   }
 else
-  # have "cp -ral"? otherwise rely on my linktree script
-  if [ "x`cp --help 2>&1 | grep ' -[ral][, ]' | wc -l | tr -d ' '`" = x3 ]
-  then
-    mklinktree(){
-      [ $# = 2 ] || { echo "Usage: mklinktree srcdir dstdir" >&2; return 2; }
-      _mkl_src=$1
-      _mkl_dst=$2
-      case "$_mkl_dst" in
-        /* | ./* ) ;; *) _mkl_dst=./$_mkl_dst ;;
+  mklinktree(){
+    [ $# = 2 ] || { echo "Usage: mklinktree srcdir dstdir" >&2; return 2; }
+    (
+      set -ue
+      src=$1 dst=$2
+      [ -d "$src/" ] || {
+        echo "mklinktree: missing srcdir: $src" >&2
+        exit 1
+      }
+      [ ! -e "$dst" ] || {
+        echo "mklinktree: existing dstdir: $dst" >&2
+        exit 1
+      }
+      case "$src" in
+        /*) ;; *) src=$(pwd)/$src ;;
+      esac
+      case "$dst" in
+        /* | ./* ) ;; *) dst=./$dst ;;
       esac
       # make link tree, might fail if hard link limit reached for files
-      $trace cp -ral "$_mkl_src" "$_mkl_dst" || {
-        # failed to make target? fail outright
-        [ -d "$_mkl_dst/." ] || return 1
-        # if we made the target, update from source
-        dorsync "$_mkl_src/" "$_mkl_dst/"
-      }
-    }
-  else
-    mklinktree(){ $trace linktree "$1" "$2"; }
-  fi
+      $trace mkdir "$dst"
+      $trace rsync -a "--link-dest=$src" "$src/" "$dst/" \
+      || dorsync "$src/" "$dst/"
+    )
+  }
 fi
 
 if [ $imode ]
