iterm: add "setvar" operation to set an iTerm user variable

diff --git a/bin/iterm b/bin/iterm
--- a/bin/iterm
+++ b/bin/iterm
@@ -13,6 +13,7 @@ usage="Usage: $cmd [-x] op [op-args...]
   Ops:
     open command [args...]
         Open new terminal window runnong command.
+    setvar varname value...
     switch-profile profile name...
         Change the current tty's profile to 'profile name...'"
 
@@ -43,6 +44,18 @@ else
       if [ $# = 0 ]
       then
         echo "$cmd: $op: missing command" >&2
+        badopts=1
+      fi
+      ;;
+    setvar)
+      if [ $# -lt 1 ]
+      then
+        echo "$cmd: $op: missing varname" >&2
+        badopts=1
+      fi
+      if [ $# -lt 2 ]
+      then
+        echo "$cmd: $op: missing value" >&2
         badopts=1
       fi
       ;;
@@ -84,9 +97,16 @@ case "$op" in
     exec $trace osascript -e "$iterm_script"
     ;;
 
+  setvar)
+    varname=$1
+    shift
+    value64=$( printf '%s' "$*" | base64 )
+    printf '\e]1337;SetUserVar=%s\a' "$value64"
+    ;;
+
   switch-profile)
     profilename=$*
-    printf ']50;SetProfile=%s' "$profilename" >/dev/tty
+    printf '\e]50;SetProfile=%s\a' "$profilename" >/dev/tty
     ;;
 
   *)echo "$cmd: $op: unimplemented op" >&2
