bin/iterm: initial impl of badge-format, not finished

diff --git a/bin/iterm b/bin/iterm
--- a/bin/iterm
+++ b/bin/iterm
@@ -11,6 +11,7 @@ trace=
 cmd=$0
 usage="Usage: $cmd [-x] op [op-args...]
   Ops:
+    badge-forma format...
     open command [args...]
         Open new terminal window runnong command.
     setvar varname value...
@@ -40,6 +41,13 @@ else
   op=$1
   shift
   case $op in
+    badge-format)
+      if [ $# = 0 ]
+      then
+        echo "$cmd: $op: missing format" >&2
+        badopts=1
+      fi
+      ;;
     open)
       if [ $# = 0 ]
       then
@@ -75,6 +83,10 @@ fi
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 case "$op" in
+  badge-format)
+    format64=$( printf '%s' "$*" | base64 )
+    printf '\e]1337;SetBadgeFormat=%s\a' "$format64"
+    ;;
   open)
     shcmd=$( shqstr "$@" )
     as_shcmd=\"$( printf '%s\n' "$shcmd" | sed 's/["\\]/\\&/g' )\"
