log-tsline: emit usage message even in the face of a bare -? option

diff --git a/bin/log-tsline b/bin/log-tsline
--- a/bin/log-tsline
+++ b/bin/log-tsline
@@ -53,15 +53,23 @@ uccat=`printf "%s\n" "$category" | tr '[a-z]' '[A-Z]'`
 [ -n "$tsdir" ] || tsdir=$HOME/$lccat/timesheets/$USER
 if [ ! -d "$tsdir/." ]
 then
-  [ $iftsdir ] && exit 0
-  echo "$cmd: missing timesheet dir: $tsdir" >&2
-  badopts=1
+  if [ -z "$iftsdir" ]
+  then
+    echo "$cmd: missing timesheet dir: $tsdir" >&2
+    badopts=1
+  fi
 else
   [ -n "$cfg" ] || cfg=$tsdir/$uccat.conf.sh
   [ -s "$cfg" ] || { echo "$cmd: missing config: $cfg" >&2; badopts=1; }
 fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
+
+if [ ! -d "$tsdir/." ]
+then
+  [ $iftsdir ]
+  exit $?
+fi
 
 . "$cfg"
 : ${TSDATEFMT_FILENAME:=$tsdir/'%Y-%m-%d'}
