mrsync: move hostlist to dst, like plain rsync - easier to use

diff --git a/bin/mrsync b/bin/mrsync
--- a/bin/mrsync
+++ b/bin/mrsync
@@ -9,18 +9,9 @@ set -ue
 trace=${DEBUG:+set-x}
 
 cmd=$0
-usage="Usage: $cmd hostlist [rsync-opts...] src dst"
+usage="Usage: $cmd [rsync-opts...] src hostlist:dst"
 
 badopts=
-
-if [ $# = 0 ]
-then
-  echo "$cmd: missing hostlist" >&2
-  badopts=1
-else
-  hostlist=$1
-  shift
-fi
 
 if [ $# -lt 2 ]
 then
@@ -38,6 +29,15 @@ else
     [ $pos = 1 ] && set --
     [ $pos = $nargs ] || set -- ${1+"$@"} "$arg"
   done
+  case "$dst" in
+    *:*)
+      hostlist=`expr "x$dst" : 'x\([^:]*\):.*'`
+      dst=`expr "x$dst" : 'x[^:]*:\(.*\)'`
+      ;;
+    *)echo "$cmd: dst: missing hostlist: $dst" >&2
+      badopts=1
+      ;;
+  esac
 fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
