muttedit: new "-w wprog" option to dispatch composition in separate terminal window

diff --git a/bin/muttedit b/bin/muttedit
--- a/bin/muttedit
+++ b/bin/muttedit
@@ -11,11 +11,21 @@
 
 set -ue
 
+: ${TMPDIR:=/tmp}
+
+wprog=${MUTTEDIT_WINDOWPROG:-}
+
 cmd=$0
 usage="Usage:
-  $cmd [-d] filename    Start a new message in mutt based on filename.
-    -d  Start session detached.
-  $cmd reopen           Open sessions for all mutt editor files sitting about."
+  $cmd [-d] [-w wprog] filename
+    Start a new message in mutt based on filename.
+    -d          Start session detached.
+    -w wprog    Invoke the submutt in wprog asynchronously.
+                This is a command prefix such as \"xterm -e\".
+  $cmd reopen
+    Open sessions for all mutt editor files sitting about."
+
+badopts=
 
 if [ $# -gt 0 ] && [ "x$1" = xreopen ]
 then
@@ -30,17 +40,62 @@ fi
 
 mode_screen=-m
 mode_tmux=
-if [ $# -gt 0 ] && [ "x$1" = x-d ]
-then
+while [ $# -gt 0 ]
+do
+  case $1 in
+    -d) bg=1
+        mode_screen='-d -m'
+        mode_tmux=-d
+        ;;
+    -w) wprog=$2; shift ;;
+    --) shift; break ;;
+    -?*)echo "$cmd: unrecognised option: $1" >&2
+        badopts=1
+        ;;
+    *)  break ;;
+  esac
   shift
-  mode_screen='-d -m'
-  mode_tmux=-d
+done
+
+bg=
+[ -n "$wprog" ] && bg=1
+
+if [ $# -gt 0 ]
+then
+  filename=$1
+  shift
+  [ -s "$filename" ] || {
+    echo "$cmd: expected non-empty file, got: $filename" >&2
+    badopts=1
+  }
+  else
+  echo "$cmd: missing filename" >&2
+  badopts=1
 fi
 
-[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
-filename=$1; shift
+[ $# = 0 ] || {
+  echo "$cmd: extra arguments: $*" >&2
+  badopts=1
+}
 
-[ -s "$filename" ] || { echo "$cmd: expected non-empty file, got: $filename" >&2; exit 2; }
+[ $badopts ] && {
+  echo "$usage" >&2
+  exit 2
+}
+
+if [ $bg ]
+then
+  tmpf=$TMPDIR/muttedit.$$
+  ( umask 077; cp -- "$filename" "$tmpf" ) || exit 1
+  filename=$tmpf
+fi
+
+if [ -n "$wprog" ]
+then
+  # run muttedit in a terminal with the copied template
+  $wprog "$0" -w '' "$filename" </dev/null >&2 &
+  exit 0
+fi
 
 now=$( date '+%d%b%Y-%H:%M'|tr '[A-Z]' '[a-z]' )
 subj=$( sed -n -e '/^$/q; y/	/ /; /^[Ss]ubject:/{ s/^[^:]*: *//; s/[^a-zA-Z0-9:]/_/g; s/___*/_/g; p; q; }' <"$filename" | tr : _ )
