pg-util: add "dump -d dumpdir" operation

diff --git a/bin/pg-util b/bin/pg-util
--- a/bin/pg-util
+++ b/bin/pg-util
@@ -10,12 +10,21 @@ cmd=`basename "$0"`
 usage="Usage:
   -U pg-user    PostgreSQL database user. Default from \$USER or \`id -un\`.
   -x            Trace execution. With \"grant\", apply the GRANTs instead
-                of reciting them.
-  $cmd [-U pg-user] [-x]
+                of reciting them. Implies -y.
+  -y            Perform actions instead of reciting them.
+
+  $cmd [-U pg-user] [-x] [-y]
         List database names.
-  $cmd [-U pg-user] [-x] database [ls]
+  $cmd [-U pg-user] [-x] [-y] database [ls]
         List database relations (tables, etc).
-  $cmd [-U pg-user] [-x] databases,... grant grants,... [on tables,...] to pg-role
+  $cmd [-U pg-user] [-x] [-y] databases,... dump -d dumpdir
+        Call pg_dump on the specified databases, writing compressed
+        \"plain\" dump files into the specified dumpdir using pg_dump,
+        using rewriteif to avoid replacing unchanged dumps, and to make
+        distinct new files when changed.
+        The database name \"ALL\" will recurse over all databases except
+        \"template0\".
+  $cmd [-U pg-user] [-x] [-y] databases,... grant grants,... [on tables,...] to pg-role
         Recite or apply the specified GRANTs.
         The database name \"ALL\" will recurse over all databases except
         \"template0\".
@@ -27,7 +36,7 @@ pg_database=
 doit=
 trace=
 [ -t 2 ] && trace=set-x
-xopt=
+subopts=
 
 badopts=
 
@@ -35,7 +44,8 @@ while [ $# -gt 0 ]
 do
   case "$1" in
     -U) pg_user=$2; shift ;;
-    -x) xopt=$1 doit=1 trace=set-x ;;
+    -x) subopts="$subopts $1" doit=1 trace=set-x ;;
+    -y) subopts="$subopts $1" doit=1 ;;
     --) shift; break ;;
     -?*)echo "$cmd: unrecognised option: $1" >&2
         badopts=1
@@ -61,6 +71,33 @@ then
   else  op=$1; shift
   fi
   case "$op" in
+
+    dump)
+      dumpdir=
+      while [ $# -gt 0 ]
+      do
+        case "$1" in
+          -d)   dumpdir=$2; shift ;;
+          --)   shift; break ;;
+          -?*)  echo "$cmd: $op: unrecognised option: $1" >&2
+                badopts=1
+                ;;
+          *)    break ;;
+        esac
+        shift
+      done
+      if [ -z "$dumpdir" ]
+      then
+        echo "$cmd: $op: missing -d dumpdir option" >&2
+        badopts=1
+      else
+        if [ ! -d "$dumpdir/." ]
+        then
+          echo "$cmd: $op: -d $dumpdir: not a directory" >&2
+          badopts=1
+        fi
+      fi
+      ;;
 
     grant)
       if [ $# = 0 ]
@@ -119,22 +156,34 @@ fi
 
 # call ourself with supplied post-option arguments
 recurse()
-{ $trace "$0" -U "$pg_user" $xopt -- ${1+"$@"}
+{ $trace "$0" -U "$pg_user" $subopts -- ${1+"$@"}
 }
 
 case "$op" in
 
+  dump)
+    case "$pg_database" in
+      ALL)  pg_database=$( recurse | grep -v '^template0$' ) ;;
+      *,*)  pg_database=$( echo "$pg_database" | tr , ' ' ) ;;
+    esac
+    for db in $pg_database
+    do  set -- pg_dump -F p "$db"
+        dumpfile=$dumpdir/$db.sql.gz
+        if [ $doit ]
+        then  $trace "$@" | $trace gzip -n | $trace rewriteif -N "$dumpfile"
+        else  echo "$*"
+        fi
+    done
+    ;;
+
   grant)
     case "$pg_database" in
       ALL)
-        if [ "x$pg_database" = xALL ]
-        then
-          for db in $( recurse | grep -v '^template0$' )
-          do
-            recurse "$db" grant "$pg_grants" on "$pg_tables" to "$pg_role"
-          done
-          exit $?
-        fi
+        for db in $( recurse | grep -v '^template0$' )
+        do
+          recurse "$db" grant "$pg_grants" on "$pg_tables" to "$pg_role"
+        done
+        exit $?
         ;;
       *,*)
         for db in `echo "$pg_database" | tr , ' '`
