pull-user: fix up error message

diff --git a/bin/pull-user b/bin/pull-user
--- a/bin/pull-user
+++ b/bin/pull-user
@@ -62,7 +62,7 @@ else
         fi
         ;;
     *@?*);;
-    *)  echo "$cmd: invalue user@host: $remote" >&2
+    *)  echo "$cmd: invalid user@host: $remote" >&2
         badopts=1
         ;;
   esac
