add py3x+ scripts, tweak py2x+ scripts

diff --git a/bin/py26+ b/bin/py26+
--- a/bin/py26+
+++ b/bin/py26+
@@ -1,5 +1,5 @@
 #!/bin/sh
-which python2.6 >/dev/null 2>&1 && exec python2.6 ${1+"$@"}
 which python2.7 >/dev/null 2>&1 && exec python2.7 ${1+"$@"}
-echo "$0: no python 2.6 or 2.7, skipping: $0 $*" >&2
+which python2.6 >/dev/null 2>&1 && exec python2.6 ${1+"$@"}
+echo "$0: no python 2.7 or 2.6, aborting: $0 $*" >&2
 exit 1
