s3-clone-webite: add --no-wget and --no-sync options to skip phases

diff --git a/bin/s3-clone-website b/bin/s3-clone-website
--- a/bin/s3-clone-website
+++ b/bin/s3-clone-website
@@ -8,10 +8,27 @@ set -ue
 
 : ${S3CFG:=$HOME/.s3cfg-$AWS_ID}
 
+no_wget=
+no_sync=
+
 cmd=$( basename "$0" )
-usage="Usage: $cmd fqdn s3-bucket-name"
+usage="Usage: $cmd [--no-wget] [--no-sync] fqdn s3-bucket-name"
 
 badopts=
+
+while [ $# -gt 0 ]
+do
+  case "$1" in
+    --no-sync)  no_sync=1 ;;
+    --no-wget)  no_wget=1 ;;
+    --)         shift; break ;;
+    -?*)        echo "$cmd: unrecognised option: $1" >&2
+                badopts=1
+                ;;
+    *)          break ;;
+  esac
+  shift
+done
 
 if [ $# = 0 ]
 then  echo "$cmd: missing fqdn" >&2
@@ -49,20 +66,24 @@ setx(){
 
 xit=0
 
-setx wget -q -mp "$srcurl" || { echo "$cmd: warning: wget had errors, rerun with -nv for details" >&2; xit=1; }
-cd "$vhsubdir"
-setx s3 -MP sync . "$dsturl"
-# repair
-for fixext in text/css:.css
-do
-  mimetype=$( expr "x$fixext" : 'x\(.*\):.*' )
-  suffix=$(   expr "x$fixext" : 'x.*:\(.*\)' )
-  find * -type f -name "*$suffix" \
-  | while read -r fixfile
-    do
-      ##setx s3 del "$dsturl/$fixfile"
-      setx s3 -P -m "$mimetype" put "$fixfile" "$dsturl/$fixfile"
-    done
-done
+[ $no_wget ] || setx wget -q -mp "$srcurl" || { echo "$cmd: warning: wget had errors, rerun with -nv for details" >&2; xit=1; }
+
+if [ -z "$no_sync" ]
+then
+  cd "$vhsubdir"
+  setx s3 -MP sync . "$dsturl"
+  # repair
+  for fixext in text/css:.css
+  do
+    mimetype=$( expr "x$fixext" : 'x\(.*\):.*' )
+    suffix=$(   expr "x$fixext" : 'x.*:\(.*\)' )
+    find * -type f -name "*$suffix" \
+    | while read -r fixfile
+      do
+        ##setx s3 del "$dsturl/$fixfile"
+        setx s3 -P -m "$mimetype" put "$fixfile" "$dsturl/$fixfile"
+      done
+  done
+fi
 
 exit $xit
