s3-clone-website: accept --password=username:areaname to imply a credentials file for Basic Authentication protected source sites

diff --git a/bin/s3-clone-website b/bin/s3-clone-website
--- a/bin/s3-clone-website
+++ b/bin/s3-clone-website
@@ -12,24 +12,29 @@ no_wget=
 no_sync=
 no_fixmime=
 htdocs_dir=
+ht_userarea=
 
 cmd=$( basename "$0" )
 usage="Usage: $cmd [--no-wget] [--no-sync] [-d htdocs-dir] fqdn s3-bucket-name
   --no-fixmime  Do not update the MIME types of problem extensions.
   --no-sync     Do not update the S3 bucket from the htdocs tree.
   --no-wget     Do not update the htdocs tree from the source website.
+  --password username:areaname
+                Read password for username from .password-areaname.
   -d htdocs-dir
             Use the specified directory as the htdocs tree; the default is
             taken from the FQDN."
 
 badopts=
 
+set -x
 while [ $# -gt 0 ]
 do
   case "$1" in
     --no-fixmime)   no_fixmime=1 ;;
     --no-sync)      no_sync=1 ;;
     --no-wget)      no_wget=1 ;;
+    --password)     ht_userarea=$2; shift ;;
     -d)             htdocs_dir=$2; shift ;;
     --)             shift; break ;;
     -?*)            echo "$cmd: unrecognised option: $1" >&2
@@ -39,6 +44,30 @@ do
   esac
   shift
 done
+
+# sanity check ht credentials
+if [ -n "$ht_userarea" ]
+then
+    case "$ht_userarea" in
+      ?*:?*)
+        ht_username=$( expr "x$ht_userarea" : 'x\([^:]*\):.*' )
+        ht_areaname=$( expr "x$ht_userarea" : 'x[^:]*:\(.*\)' )
+        ht_password_file=$HOME/.htpassword-$ht_areaname
+        if [ ! -s "$ht_password_file" ]
+        then
+          echo "$cmd: missing credentials file: $ht_password_file" >&2
+          badopts=1
+        else
+          ht_password=$(<$ht_password_file)
+        fi
+        ;;
+      *)echo "$cmd: invalid arguments to --password, expected \"username:areaname\"" >*2
+        badopts=1
+        ;;
+    esac
+else
+  ht_username=
+fi
 
 if [ $# = 0 ]
 then  echo "$cmd: missing fqdn" >&2
@@ -61,6 +90,7 @@ then
 fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
+set +x
 
 srcurl=http://$fqdn/
 dsturl=s3://$s3bucket
@@ -80,7 +110,15 @@ cd "$htdocs_dir"
 
 if [ -z "$no_wget" ]
 then
-  setx wget -q -mp -nH "$srcurl" \
+  set -- wget -q -mp -nH
+  recite=$*
+  if [ -n "$ht_username" ]
+  then
+    set -- "$@" "--user=$ht_username" "--password=$ht_password"
+    recite="$recite --user=$ht_username --password=******"
+  fi
+  echo "$recite $srcurl" >&2
+  "$@" "$srcurl" \
   || { echo "$cmd: warning: wget had errors, rerun with -nv for details" >&2; xit=1; }
 fi
 
