tm: add command line parsing for use-session-remote; tweak parsing for use-session
--HG--
branch : tmux

diff --git a/bin/tm b/bin/tm
--- a/bin/tm
+++ b/bin/tm
@@ -198,11 +198,34 @@ case "$op" in
     else
       session_name=$1
       shift
-      if [ $# -gt 0 ]
-      then
-        echo "$cmd: $op $session_name: extra arguments: $*" >&2
-        badopts=1
-      fi
+    fi
+    if [ $# -gt 0 ]
+    then
+      echo "$cmd: $op: extra arguments: $*" >&2
+      badopts=1
+    fi
+    ;;
+  use-session-remote)
+    if [ $# = 0 ]
+    then
+      echo "$cmd: $op: missing session-name" >&2
+      badopts=1
+    else
+      session_name=$1
+      shift
+    fi
+    if [ $# = 0 ]
+    then
+      echo "$cmd: $op: missing remote-host" >&2
+      badopts=1
+    else
+      remote_host=$1
+      shift
+    fi
+    if [ $# -gt 0 ]
+    then
+      echo "$cmd: $op: extra arguments: $*" >&2
+      badopts=1
     fi
     ;;
   *)echo "$cmd: unrecognised op: $op" >&2
