vbox: add mkvdi to convert raw disc image to .vdi file

diff --git a/bin/vbox b/bin/vbox
--- a/bin/vbox
+++ b/bin/vbox
@@ -12,6 +12,7 @@ trace=
 cmd=$( basename "$0" )
 usage="Usage: $cmd op [arguments...]
   Operations:
+    mkvdi img [VBoxManage convertfromraw options...]
     pause vm-name [VBoxManage controlvm vm-name pause options...]
     resume vm-name [VBoxManage controlvm vm-name resume options...]
     start vm-name [VBoxManage startvm options...]
@@ -27,6 +28,21 @@ else
   op=$1
   shift
   case "$op" in
+    mkvdi)
+        if [ $# = 0 ]
+        then
+          echo "$cmd: $op: missing image filename" >&2
+          badopts=1
+        else
+          imgfile=$1
+          shift
+          if [ ! -s "$imgfile" ]
+          then
+            echo "$cmd: $op: need nonempty file: $imgfile" >&2
+            bdopts=1
+          fi
+        fi
+        ;;
     pause|resume|start|suspend)
         if [ $# = 0 ]
         then
@@ -46,6 +62,15 @@ fi
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 case "$op" in
+  mkvdi)    case "$imgfile" in
+              *.img | *.raw )
+                vdifile=$( expr "x$imgfile" : 'x\(.*\)\....' ).vdi
+                ;;
+              *)vdifile=$imgfile.vdi
+                ;;
+            esac
+            $trace VBoxManage convertfromraw "$imgfile" "$vdifile" --format VDI ${1+"$@"}
+            ;;
   pause)    $trace VBoxManage controlvm "$vmname" pause ${1+"$@"} ;;
   resume)   $trace VBoxManage controlvm "$vmname" resume ${1+"$@"} ;;
   start)    $trace VBoxManage startvm "$vmname" ${1+"$@"} ;;
