Take copy of data file if backgrounding a tty window. Delete data file _after_ terminal exits. [CVS rev 1.14]

diff --git a/apphelper b/apphelper
--- a/apphelper
+++ b/apphelper
@@ -109,14 +109,24 @@ else
 	    echo "$cmd: bad file?" >&2
 	    ls -ld "$file" >&2
 	    badopts=1
+      else
+	    if [ $doterm ]
+	    then
+		if cp "$file" "$tmpfile"
+		then  file=$tmpfile
+		else  echo "$cmd: can't cp $file to $tmpfile, aborting" >&2
+		      badopts=1
+		fi
+	    fi
       fi
   fi
 
   # fork off a terminal if need be
   if [ $doterm ]
   then
-      term -n "$termname" +a +ip -small -e "$0" +t "$file" ${1+"$@"}
-      rm -f "$tmpfile"
+      ( term -n "$termname" +a +ip -small -e "$0" +t "$file" ${1+"$@"}
+	rm -f "$tmpfile"
+      ) &
       exit 0
   fi
 
