Recite chosen CDDB record for approval or edit. Recite cdparanoia error tail. [CVS rev 1.21]

diff --git a/cdrip b/cdrip
--- a/cdrip
+++ b/cdrip
@@ -64,7 +64,7 @@ esac
 toc=/tmp/cdtoc.$$
 cdtoc "$dev" >"$toc" || { rm -f "$toc"; exit 1; }
 
-cat "$toc"
+grep '^[^#]' <"$toc" | grep -v '^[0-9][0-9]* '
 ask "Edit TOC before use" && $EDITOR "$toc"
 
 exec <"$toc"
@@ -145,7 +145,8 @@ sed -e 's;//*; -- ;g' -e 's/   */ /g' \
 	  ) &
 	  encpid=$!
       else
-	  echo "cdparanoia failed" >*2
+	  echo "cdparanoia failed" >&2
+	  tail -20 cdp.err >&2
 	  rm -f "$raw"
 	  xit=1
       fi
