Set EDITOR at top. Consult the CDDBD to compute the discid as the perl modules are busted. [CVS rev 1.3]

diff --git a/cdsubmit b/cdsubmit
--- a/cdsubmit
+++ b/cdsubmit
@@ -17,6 +17,8 @@ submitto=$testsubmit
 cachesave=
 doedit=
 
+EDITOR=${EDITOR:-vi}
+
 usage="Usage: $cmd [-entf] [-m addr] category
 	-e	Invoke editor to enter information.
 	-n	No action. Emit submission email on standard output.
@@ -90,8 +92,10 @@ read ntracks || { echo "$cmd: no track count" >&2; exit 1; }
 
 # stash offsets in $@
 totallen=0
+discidqry=
 while read tn len offset
 do  set ${1+"$@"} "$offset"
+    discidqry="$discidqry $offset"
     totallen=`expr $totallen + $len`
     [ $# = $tn ] || { echo "$cmd: bad track number $tn: expected $#" >&2
 		      exit 1
@@ -100,6 +104,27 @@ done
 
 # restore stdin
 exec 0<&3 3<&-
+
+# obtain discid by asking the CDDB
+cddbhost=cddb
+cddbport=888
+case "$CDDBSERVER" in
+    *:*)	cddbhost=`expr "x$CDDBSERVER" : 'x\(.*\):.*'`
+    		cddbport=`expr "x$CDDBSERVER" : 'x.*:\(.*\)'`
+		;;
+esac
+discidqry="DISCID $# $discidqry $totallen"
+odiscid=$discid
+discid=`
+	( echo "CDDB HELLO $USER $HOSTNAME $cmd $version"
+	  echo "$discidqry"
+	  echo "QUIT"
+	) | nc "$cddbhost" "$cddbport" | sed -n 's/^200 Disc ID is \\([0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]\\)/\\1/p'
+       `
+case "$discid" in
+    [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]) ;;
+    *)	echo "$cmd: invalid discid \"$discid\"" >&2; exit 1 ;;
+esac
 
 # construct description file
 if [ $doedit ]
@@ -118,7 +143,7 @@ then
     ) >"$desc"
 
     # edit file and then clean it up for easy parsing
-    ${EDITOR:-vi} "$desc" || { echo "$cmd: edit fails, aborting" >&2; exit 1; }
+    $EDITOR "$desc" || { echo "$cmd: edit fails, aborting" >&2; exit 1; }
 else
     ( echo "Discid: $discid" >"$desc"
       necho "Artist: " >&2; read -r artist || exit 1
@@ -244,7 +269,7 @@ ask "Is the above all ok" \
 	   }
 if ask "Edit the cddb record before submission"
 then
-    ${EDITOR:-vi} "$cddb" || { echo "$cmd: edit fails, aborting" >&2; exit 1; }
+    $EDITOR "$cddb" || { echo "$cmd: edit fails, aborting" >&2; exit 1; }
     ask "Still ok" \
 	|| { echo "$cmd: aborting, cddb saved in $cddb, desc saved in $desc" >&2
 	     exit 1
@@ -283,7 +308,7 @@ fi
   ## quoted-printable <"$cddb"
 ) | if [ -n "$submitto" ]
     then
-      (set -x; sendmail -oi -t)
+      (set -x; sendmail -oi "$submitto")
     else
       exec cat
     fi
