More fixes and an ugly workaround for a bug in GNU sed. [CVS rev 1.2]

diff --git a/cdsubmit b/cdsubmit
--- a/cdsubmit
+++ b/cdsubmit
@@ -151,14 +151,14 @@ else
 fi
 
 # strip header tags
-sed -n 's/^[^:]*: *//p' "$desc" >"$tmp" || exit 1
+sed '1,/^$/s/^[^:]*: *//' "$desc" >"$tmp" || exit 1
 
 # load data from file
 # and construct CDDB entry
 exec 3<&0 0<"$tmp" 4>&1 1>"$cddb"
 ok=1
 
-# start o nthe CDDB stuff
+# start the CDDB stuff
 echo "# xmcd CD database file generated by $cmd"
 echo "#"
 
@@ -172,7 +172,8 @@ echo "# Disc length: $totallen seconds"
 echo "#"
 
 echo "# Revision: 0"
-echo "# submitted via; $cmd $version by Cameron Simpson <cs@zip.com.au>"
+echo "# Submitted via: $cmd $version by Cameron Simpson <cs@zip.com.au>"
+echo "#"
 
 read -r dummydiscid || exit 1
 [ "x$discid" = "x$dummydiscid" ] || { echo "$cmd: discid damaged" >&2; exit 1; }
@@ -203,7 +204,6 @@ do
     if [ -n "$ttitle" ]
     then
 	echo "TTITLE$n=$ttitle"
-	echo "EXTT$n="
 	n=`expr $n + 1`
 	tn=`expr $tn + 1`
     else
@@ -212,11 +212,25 @@ do
     fi
 done
 
-echo "PLAYORDER="
-echo
+# anything else on the input is extended data
+# NB: this used to be a plain sed invocation:
+#	sed -n '/[^ 	]/s/^/EXTD=/p'
+#     but there's a great bug in Linux sed
+#     where they've stuffed up mmap()ed I/O
+#     and lose the read pointer :-(
+#     Bug report and patch submitted!
+while read -r line
+do  echo "EXTD=$line"
+done
 
-# anything else is extended data
-sed -n '/[^ 	]/s/^/EXTD=/p'
+n=0
+for offset
+do
+    echo "EXTT$n="
+    n=`expr $n + 1`
+done
+
+echo "PLAYORDER="
 
 # restore stdin and stdout
 exec 0<&3 3<&- 1>&4 4>&-
@@ -224,8 +238,18 @@ exec 0<&3 3<&- 1>&4 4>&-
 [ $ok ] || exit 1
 
 # sanity check
-ask "Is the above all ok" || exit 1
-ask "Edit the cddb record before submission" && ${EDITOR:-vi} "$cddb"
+ask "Is the above all ok" \
+	|| { echo "$cmd: aborting, cddb saved in $cddb, desc saved in $desc" >&2
+	     exit 1
+	   }
+if ask "Edit the cddb record before submission"
+then
+    ${EDITOR:-vi} "$cddb" || { echo "$cmd: edit fails, aborting" >&2; exit 1; }
+    ask "Still ok" \
+	|| { echo "$cmd: aborting, cddb saved in $cddb, desc saved in $desc" >&2
+	     exit 1
+	   }
+fi
 
 if [ $cachesave ]
 then
