Allow envvar $REMOTE_USER to override auth check - just believe it.

diff --git a/cgihtnisauth b/cgihtnisauth
--- a/cgihtnisauth
+++ b/cgihtnisauth
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
 # Script to require UNIX NIS login for a CGI script.
+# If the CGI envvar $REMOTE_USER is already set, just echo it and get out.
 #	- Cameron Simpson <cs@zip.com.au> 12feb2001
 #
 # Exit status: 0 for a match, with userid on stdout.
@@ -18,26 +19,31 @@
 # and continues with the login name in $userid on auth success.
 #
 
-authhdr=$HTTP_AUTHORIZATION
-realm="UNIX Login"
+userid=${REMOTE_USER:-''}
+if [ -z "$userid" ]
+then
 
-[ -n "$authhdr" ] \
-|| { echo "Status: 401"
-     echo "WWW-Authenticate: Basic realm=\"$realm\""
-     echo "Content-Type: text/plain"
-     echo
-     echo "Authorisation needed for realm \"$realm\"."
-     exit 1
-   }
+  authhdr=$HTTP_AUTHORIZATION
+  realm="UNIX Login"
 
-userid=`htnisauth` \
-|| { echo "Status: 401"
-     echo "WWW-Authenticate: Basic realm=\"$realm\""
-     echo "Content-Type: text/plain"
-     echo
-     echo "Invalid authorisation for realm \"$realm\"."
-     exit 1
-   }
+  [ -n "$authhdr" ] \
+  || { echo "Status: 401"
+       echo "WWW-Authenticate: Basic realm=\"$realm\""
+       echo "Content-Type: text/plain"
+       echo
+       echo "Authorisation needed for realm \"$realm\"."
+       exit 1
+     }
+
+  userid=`htnisauth` \
+  || { echo "Status: 401"
+       echo "WWW-Authenticate: Basic realm=\"$realm\""
+       echo "Content-Type: text/plain"
+       echo
+       echo "Invalid authorisation for realm \"$realm\"."
+       exit 1
+     }
+fi
 
 echo "$userid"
 exit 0
