Amend error message to mention -py extensions. [CVS rev 1.7]

diff --git a/cgiwrap b/cgiwrap
--- a/cgiwrap
+++ b/cgiwrap
@@ -100,7 +100,7 @@ else  if [ -s "$SCRIPT_FILENAME-sh" ]
 	    then  python "$SCRIPT_FILENAME-py" ${1+"$@"}
 	    else  if [ -s "$SCRIPT_FILENAME-ici" ]
 		  then  ici "$SCRIPT_FILENAME-ici" ${1+"$@"}
-		  else  echo "$0: can't find $SCRIPT_FILENAME-{sh,pl,ici}" >&2
+		  else  echo "$0: can't find $SCRIPT_FILENAME-{sh,pl,py,ici}" >&2
 		  fi
 	    fi
       fi
