Bugfix "-r rev" option test. [CVS rev 1.2]

diff --git a/cvsdiff-rev b/cvsdiff-rev
--- a/cvsdiff-rev
+++ b/cvsdiff-rev
@@ -28,13 +28,14 @@ fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
-[ -z "$rev" ] || rev=`cvsrev "$file"` || exit 1
+[ -n "$rev" ] || rev=`cvsrev "$file"` || exit 1
 
-if [ "x$rev" = x1.1 ]
-then
-  echo "$cmd: $file: no diff available for revision $rev" >&2
-  exit 1
-fi
+case "$rev" in
+  *.1)
+    echo "$cmd: $file: can't produce diff for revision $rev" >&2
+    exit 1
+    ;;
+esac
 
 revmaj=`expr "x$rev" : 'x\([0-9][0-9]*\).*'`
 revmin=`expr "x$rev" : 'x[0-9][0-9]*\.\([0-9][0-9]*\)'`
