await: turn into trivial wrapper for forever. forever: add "!" option and change -e to -E for await.

diff --git a/forever b/forever
--- a/forever
+++ b/forever
@@ -7,26 +7,35 @@
 : ${VARRUN:=$HOME/var/run}
 
 cmd=`basename "$0"`
-usage="Usage: $cmd [-d delay] [-e] [-n num] command [args...]
-  -d delay      Delay this many seconds before the next invocation.
-  -e            Exit on error.
-  -n num        Run this many times. Default: forever.
-  -p pidfile    Record main pid in file.
-  -x            Trace execution."
+usage="Usage:
+  $cmd [!] [-d delay] [-E] [-n num] command [args...]
+  $cmd [!] [-d delay] [-E] [-n num] -c shcmd
+    !           Invert exit status for \"error\" - used by await(1cs).
+    -c shcmd    Use shell command shcmd instead of argument list.
+    -d delay    Delay this many seconds before the next invocation.
+    -E          Exit on error.
+    -n num      Run this many times. Default: forever.
+    -p pidfile  Record main pid in file.
+    -x          Trace execution."
 
+doshcmd=
+shcmd=
 delay=0
 failok=1
 max=0
 dotrace=
 pidfile=
+not=
 
 badopts=
 
 while [ $# -gt 0 ]
 do
   case $1 in
+    !)  not=1 ;;
+    -c) doshcmd=1 shcmd=$2; shift ;;
     -d) delay=$2; shift ;;
-    -e) failok= ;;
+    -E) failok= ;;
     -n) max=$2; shift ;;
     -p) pidfile=$2; shift
         case $pidfile in
@@ -44,11 +53,24 @@ do
   shift
 done
 
-[ $# -gt 0 ] || { echo "$cmd: missing command" >&2
-                  badopts=1
-                }
+if [ $doshcmd ]
+then
+  if [ $# = 0 ]
+  then
+    set -- sh -c "$shcmd"
+  else
+    echo "$cmd: extra arguments after options with -c: $*" >&2
+    badopts=1
+  fi
+else
+  [ $# -gt 0 ] || { echo "$cmd: missing command and no -c" >&2
+                    badopts=1
+                  }
+fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
+
+[ $not ] && set -- not "$@"
 
 if [ -n "$pidfile" ]
 then
@@ -64,7 +86,10 @@ do
     exec "$@"
   ) \
   || [ $failok ] \
-  || exit 1
+  || if [ $not ]
+     then  exit 0
+     else  exit 1
+     fi
 
   if [ "x$max" != x0 ]
   then
