Fix typo. [CVS rev 1.9]

diff --git a/fvwm-menu-imlist b/fvwm-menu-imlist
--- a/fvwm-menu-imlist
+++ b/fvwm-menu-imlist
@@ -43,7 +43,7 @@ done
 
 if [ $# = 0 ]
 then
-    echo "$cmd: missindir dir" >&2
+    echo "$cmd: missing dir" >&2
     badopts=1
 else
     dir=$1; shift
