Support -o option to OR patterns instead of AND. Adjust Usage to make it clear we're using sed-regexps. [CVS rev 1.3]

diff --git a/grepall b/grepall
--- a/grepall
+++ b/grepall
@@ -6,7 +6,17 @@
 
 cmd=$0
 
-[ $# = 0 ] && { echo "Usage: $cmd regexps..." >&2; exit 2; }
+[ $# = 0 ] && { echo "Usage: $cmd [-o] sed-regexps..." >&2; exit 2; }
+
+any=
+[ "x$1" = x-o ] && { any=1; shift; }
+
+if [ $# = 0 ]
+then
+    echo "$cmd: missing sed-regexps" >&2
+    echo "$usage" >&2
+    exit 2
+fi
 
 ok=1
 
@@ -22,9 +32,14 @@ do
 		;;
   esac
 
-  set x ${1+"$@"} -e "/$word/!d"; shift
+  if [ $any ]
+  then set x ${1+"$@"} -e "/$word/b ok"; shift
+  else set x ${1+"$@"} -e "/$word/!d"; shift
+  fi
 done
 
 [ $ok ] || exit 1
+
+[ $any ] && { set x ${1+"$@"} -e d -e ':ok'; shift; }
 
 exec sed "$@"
