Discard dirs-only post-cp-rpl rsync. Profit small, cost high on big trees. [CVS rev 1.24]

diff --git a/histbackup b/histbackup
--- a/histbackup
+++ b/histbackup
@@ -317,14 +317,8 @@ xit=0
 if [ -n "$lastbackup" -a -d "$dest/$lastbackup/." ]
 then
     $echo "existing backup: linking $lastbackup to $thisbackup ..."
-    if mklinktree "$dest/$lastbackup" "$dest/$thisbackup"
-    then
-	# now fix the dirs made by linktree
-	$trace rsync -a '--include=*/' --exclude='*' \
-		"$dest/$lastbackup/." "$dest/$thisbackup/."
-    else
-	echo "$cmd: warning: mklinktree $dest/$lastbackup $dest/$thisbackup fails" >&2
-    fi
+    mklinktree "$dest/$lastbackup" "$dest/$thisbackup" \
+    || echo "$cmd: warning: mklinktree $dest/$lastbackup $dest/$thisbackup fails" >&2
 
     if [ $linkonly ]
     then
