Fix var typo. Redo lock sequence logic. Strip some debugging. [CVS rev 1.2]

diff --git a/hotfwd b/hotfwd
--- a/hotfwd
+++ b/hotfwd
@@ -22,9 +22,9 @@ then
   shift; shift
   case "$locarg" in
     *:*:*)
-      location=`expr "x$logarg" : 'x\([^:]*\):.*'`
-      rhost=`expr "x$logarg" : 'x[^:]*:\([^:]*\):.*'`
-      rport=`expr "x$logarg" : 'x[^:]*:[^:]*:\(.*\)'`
+      location=`expr "x$locarg" : 'x\([^:]*\):.*'`
+      rhost=`expr "x$locarg" : 'x[^:]*:\([^:]*\):.*'`
+      rport=`expr "x$locarg" : 'x[^:]*:[^:]*:\(.*\)'`
       ;;
     *)echo "$cmd: bad argument to -l: $locarg" >&2
       badopts=1
@@ -79,47 +79,50 @@ locked()
   lockname=$1; shift
 
   lockdir=$LOCKDIR/hotfwd-$lockname
-  $trace [ -d "$lockdir/." ]
+  [ -d "$lockdir/." ]
 }
 
-# portfwd active? just use it!
-locked "portfwd-$fwdsite" && exec $trace tcpio -k localhost "$localport"
+# short path if tunnel is up
+locked "tunnel-$fwdsite" && exec $trace tcpio -k localhost "$localport"
 
-# fire up portfwd then use it
-getlock "testfwd-$fwdsite" || exit 1
-locked "portfwd-$fwdsite" \
+# do a locking check for the tunnel being active
+getlock "test-$fwdsite" || exit 1
+
+locked "tunnel-$fwdsite" \
 || \
-(
-  getlock "portfwd-$fwdsite" || { freelock "test-$fwdsite"
-				  exit 1
-				}
+  (
+    getlock "wait-$fwdsite" || { freelock "test-$fwdsite"
+				 exit 1
+			       }
 
-  getlock "wait-$fwdsite" || { freelock "test-$fwdsite"
-			       freelock "portfwd-$fwdsite"
-			       exit 1
-			     }
+    ( exec </dev/null
+      while :
+      do    echo . || break
+	    sleep $pingsleep || break
+      done
+    ) \
+    | $trace ssh "$@" "$fwdsite" 'while read ping; do echo .; done' \
+    | \
+    ( exec >&2
+      if read ack && getlock "tunnel-$fwdsite"
+      then
+	freelock "wait-$fwdsite"
+	while read ack
+	do    :
+	done
+	freelock "tunnel-$fwdsite"
+      else
+	freelock "wait-$fwdsite"
+      fi
+    ) \
+    &
 
-  ( exec </dev/null
-    while locked "portfwd-$fwdsite"
-    do    echo . || break
-	  sleep $pingsleep
+    # wait for the tunnel to come up or to fail
+    while locked "wait-$fwdsite"
+    do  sleep 1
     done
-  ) \
-  | $trace ssh "$@" "$fwdsite" 'while read ping; do echo .; done' \
-  | \
-  ( exec >/dev/null
-    while read ack
-    do    locked "wait-$fwdsite" && freelock "wait-$fwdsite"
-    done
-    locked "wait-$fwdsite" && freelock "wait-$fwdsite"
-    freelock "portfwd-$fwdsite"
-  ) \
-  &
+  )
 
-  while locked "wait-$fwdsite"
-  do  sleep 1
-  done
-)
 freelock "test-$fwdsite"
 
 exec $trace tcpio -k localhost "$localport"
