Abort instead of usage for missing pid file. [CVS rev 1.3]

diff --git a/ifpid b/ifpid
--- a/ifpid
+++ b/ifpid
@@ -33,7 +33,7 @@ else
     {  [ -s "$pidfile" -a -f "$pidfile" ] \
     && read pid etc <"$pidfile" \
     && [ -n "$pid" ]
-    } || { echo "$cmd: can't read pid from file \"$pidfile\"" >&2; badopts=1; }
+    } || { echo "$cmd: can't read pid from file \"$pidfile\"" >&2; exit 1; }
   fi
 fi
 
