Add -p option: May use parent directory if dir is a file. Trace if stderr is a tty. Drop pwd. [CVS rev 1.3]

diff --git a/incd b/incd
--- a/incd
+++ b/incd
@@ -4,9 +4,32 @@
 #	- Cameron Simpson <cs@zip.com.au> 05mar2003
 #
 
-[ $# -lt 2 ] && { echo "Usage: $cmd dir command [args...]" >&2; exit 2; }
-cd "$1" || exit 1
-shift
-pwd
-set -x
+cmd=$0
+usage="Usage: $cmd dir [-p] command [args...]
+	-p	May use parent directory if dir is a file."
+
+mayuseparent=
+
+badopts=
+
+if [ $# = 0 ]
+then  echo "$cmd: missing dir" >&2; badopts=1
+else
+  dir=$1; shift
+  [ "x$1" = x-p ] && { mayuseparent=1; shift; }
+  if [ $# = 0 ]
+  then  echo "$cmd: missing command" >&2; badopts=1
+  fi
+fi
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
+
+if [ ! -d "$dir/." ] && [ $mayuseparent ]
+then
+    parent=`dirname "$dir"`
+    [ -d "$parent/." ] && dir=$parent
+fi
+
+cd "$dir" || exit 1
+[ -t 2 ] && set -x
 exec "$@"
