Add "sh -u". If on a terminal, run a shell in the checkout if no command. [CVS rev 1.4]

diff --git a/inco b/inco
--- a/inco
+++ b/inco
@@ -1,11 +1,13 @@
-#!/bin/sh
+#!/bin/sh -u
 #
 # Run command in a temporary checkout.
 #	- Cameron Simpson <cs@zip.com.au> 04jul2003
 #
 
+: ${SHELL:=/bin/sh}
+
 cmd=`basename "$0"`
-usage="Usage: $cmd module [-f] [-r rev] command [args...]"
+usage="Usage: $cmd [-f] [-r rev] module command [args...]"
 
 badopts=
 
@@ -22,10 +24,24 @@ do
   shift
 done
 
-[ $# -lt 2 ] && { echo "$cmd: missing module or command" >&2
-		  badopts=1
-		}
-module=$1; shift
+if [ $# = 0 ]
+then
+  echo "$cmd: missing module" >&2
+  badopts=1
+else
+  module=$1
+  shift
+  if [ $# = 0 ]
+  then
+    if [ -t 0 -a -t 1 -a -t 2 ]
+    then
+      set -- "$SHELL"
+    else
+      echo "$cmd: missing command" >&2
+      badopts=1
+    fi
+  fi
+fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
