Values are now logs, with the current value being the last line. Add push and pop support. [CVS rev 1.5]

diff --git a/lastvalue b/lastvalue
--- a/lastvalue
+++ b/lastvalue
@@ -7,18 +7,36 @@
 ##echo "[$0 $*]" >&2
 
 dir=$HOME/var/log/lastvalue
+append=
+pop=
 
 cmd=$0
-Usage="Usage: $cmd [-d dir] [param [value|-]]"
+usage="Usage: $cmd [-a] [-d dir] [param [value|-]]
+	-a	Append (push) the value.
+	-p	Pop the value.
+	-d	Directory holding value files."
 
 badopts=
 
-[ "x$1" = x-d ] && { dir=$2; shift; shift; }
+while :
+do
+  case "$1" in
+    -d)	dir=$2; shift ;;
+    -a)	append=1 ;;
+    -p)	pop=1 ;;
+    --)	shift; break ;;
+    -?*)echo "$cmd: unrecognised option: $1" &>2; badopts=1 ;;
+    *)	break ;;
+  esac
+  shift
+done
 
 if [ $# = 0 ]
 then
     cd "$dir" || exit 1
-    exec grep . /dev/null *
+    for f in *
+    do  [ -s "./$f" ] && tail -1 "./$f" | sed "s/^/$f: /"
+    done
 else
     param=$1; shift
     case "$param" in
@@ -31,15 +49,32 @@ fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
-[ $# = 0 ] && exec cat "$dir/$param"
+# no args - recite value
+if [ $# = 0 ]
+then
+  [ $append ] && { echo "$cmd: value required in append mode" >&2; exit 2; }
+  tail -1 "$dir/$param" || exit 1
+  exec >/dev/null
+  [ $pop ] && lock "lastvalue_$param" bsed -s '$d' "$dir/$param"
+  exit 0
+fi
 
 exec >/dev/null
 
 needdir "$dir" || exit 1
+cd "$dir"      || exit 1
 
 if [ "x$1" = x- ]
-then
-    cat
-else
-    echo "$1"
-fi >"$dir/$param"
+then  read value || exit 1
+else  value=$1
+fi
+
+addcmd='echo "$value"'
+
+if [ $append ]
+then  addcmd="$addcmd >>\"\$param\""
+else  addcmd="$addcmd  >\"\$param\""
+fi
+
+export param value
+exec lock "lastvalue_$param" sh -c "$addcmd"
