Mykefile: add python unitests to _test, require _test for _release

diff --git a/Mykefile b/Mykefile
--- a/Mykefile
+++ b/Mykefile
@@ -62,6 +62,20 @@ _test:
           done \
           exit $$xit \
         }
+        find lib/python/cs -type f -name \*.py -print \\
+        | sort \\
+        | \\
+        { xit=0 \
+          while read -r py \
+          do \
+            unitest=`sed -n '$${/^ *unittest\.main/p;}' "$$py"` \
+            [ -n "$$unitest" ] || continue \
+            pym=`expr "x$$py" : 'xlib/python/\(.*\).py' | tr / .` \
+            env-dev -d '$.' -x python -tt -B -m "$$pym" \\
+            || { echo "FAIL: unitest $$py" >&2; exit 1; } \
+          done \
+          exit $$xit \
+        }
 
 _home:
         skip=`hg status | sed -n 's:^? \(.*\):--exclude=/\1:p'` \
@@ -111,6 +125,10 @@ _publish_bitbucket:
 
 # mark the tip as a new release
 _release:
+        :make _test
+        :make _release_force
+
+_release_force:
         cs-release add
 
 _pending:
