Only require target to be a directory if the logfile goes inside it. [CVS rev 1.3]

diff --git a/nsr-savedir b/nsr-savedir
--- a/nsr-savedir
+++ b/nsr-savedir
@@ -112,11 +112,15 @@ xit=0
 
 for dir
 do
-  [ -d "$dir" ] || { echo "$cmd: $dir: not a directory" >&2; xit=1; continue; }
-
   case "$logfile" in
-    /*)	dlogfile=$logfile ;;
-    *)	dlogfile=$dir/$logfile ;;
+    /*)	dlogfile=$logfile
+	;;
+    *)  [ -d "$dir" ] || { echo "$cmd: $dir: not a directory, can't put logfile inside" >&2
+			   xit=1
+			   continue
+			 }
+	dlogfile=$dir/$logfile
+	;;
   esac
 
   if [ $full ]
