Make prompt mandatory; drop -p option. [CVS rev 1.2]

diff --git a/readline b/readline
--- a/readline
+++ b/readline
@@ -5,9 +5,21 @@
 #	- Cameron Simpson <cs@zip.com.au> 22feb2004
 #
 
-prompt=
-[ "x$1" = x-p ] && { prompt=$2; shift; shift; }
-export prompt
+cmd=$0
+usage="Usage: readline prompt"
+
+badopts=
+
+if [ $# = 0 ]
+then
+    echo "$cmd: missing prompt" >&2
+    badopts=1
+else
+    prompt=$1; shift
+    [ $# = 0 ] || { echo "$cmd: extra arguments after prompt: $*" >&2; badopts=1; }
+fi
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 [ -t 0 ] || { echo "$0: stdin must be a tty" >&2; exit 1; }
 
