Take optional command. Add usage message. [CVS rev 1.5]

diff --git a/root@ b/root@
--- a/root@
+++ b/root@
@@ -5,13 +5,23 @@
 #
 
 cmd=$0
+usage="Usage: $cmd [-N] hostname
+       $cmd hostname command..."
+
+badopts=
 
 newflag=-N
 [ "x$1" = x-N ] && { newflag=$1; shift; }
 [ "x$1" = x+N ] && { newflag=; shift; }
 
-[ $# = 1 ] || { echo "Usage: $cmd [-N] hostname" >&2; exit 2; }
-host=$1; shift
+if [ $# = 0 ]
+then  echo "$cmd: missing hostname" >&2; badopts=1
+else  host=$1; shift
+fi
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
+
+[ $# -gt 0 ] && exec sshp1 "root@$host" "$*"
 
 ext=
 
