Drop -N option; new simpler usage needs -e option for new sessions. [CVS rev 1.17]

diff --git a/scr b/scr
--- a/scr
+++ b/scr
@@ -4,18 +4,20 @@
 #	- Cameron Simpson <cs@zip.com.au> 18may2002
 #
 
+: ${TMPDIR:=/tmp}
+: ${SHELL:=/bin/sh}
+
 cmd=$0
 usage="Usage:
     $cmd
 	List sessions.
     $cmd -A [[!]regexp...]
-	Put up terms for every screen.
-    $cmd [-c scrcmd]... [-l logfile] [-N] session-name [cmd [args...]]
+	Put up terms for all screen sessions.
+    $cmd [-c scrcmd]... [-l logfile] [session | -e cmd [args...]]
 	Join named session, creating it if missing.
 	-c scrcmd  Run the supplied screen command in addition to the .screenrc
 	-l logfile Log session to the named file.
-		   You still need to turn logging on _in_ the session:-(
-	-N	Force new session."
+		   You still need to turn logging on _in_ the session:-("
 
 # nothing? list active sessions
 [ $# = 0 ] \
@@ -25,6 +27,7 @@ usage="Usage:
 	 exit 0
        }
 
+# catch "all" mode early
 if [ "x$1" = x-A ]
 then
     shift
@@ -49,10 +52,11 @@ then
     choose=scr
     [ -n "$grepnot" ] && choose="$choose | egrep -iv \"\$grepnot\""
     [ -n "$grepfor" ] && choose="$choose | egrep -i \"\$grepfor\""
+    xit=0
     for scr in `eval "$choose" | awk '{print$1}'`
-    do  term -iconic -e scr "$scr"
+    do  term -iconic -e scr "$scr" || xit=1
     done
-    exit 0
+    exit $xit
 fi
 
 badopts=
@@ -66,7 +70,7 @@ addscrcmds()
   do
     if [ -z "$tmprc" ]
     then
-      tmprc=${TMPDIR:-/tmp}/screenrc$$
+      tmprc=$TMPDIR/screenrc$$
       cat "$rcfile" >"$tmprc" 2>/dev/null
       rcfile=$tmprc
     fi
@@ -74,11 +78,22 @@ addscrcmds()
   done
 }
 
+echo "pre args = $*"
+
+sess=
+havecmd=
+
 while :
 do
   case $1 in
     -c)	addscrcmds "$2"; shift ;;
-    -N)	new=1 ;;
+    -e)	shift
+	havecmd=1
+	[ $# = 0 ] && { echo "$cmd: -e: missing command" >&2
+			badopts=1
+		      }
+	break
+	;;
     -l)	addscrcmds "logfile $2" "logfile flush 1" "log on"; shift ;;
     --)	shift; break ;;
     -?*)echo "$cmd: unrecognised option: $1" >&2
@@ -89,30 +104,33 @@ do
   shift
 done
 
-if [ $# = 0 ]
+echo "post opts = $*"
+
+if [ $havecmd ]
 then
-  if [ $new ]
-  then
-    nsess=`scr|wc -l`
-    nsess2=`expr $nsess + 1`
-    sess=${shell:-`basename "$SHELL"`}$nsess2
-    set "$SHELL"
-  else
-    echo "$cmd: missing session-name" >&2
-    badopts=1
-  fi
+  new=1
 else
-  sess=$1; shift
-  [ $# = 0 ] && set "$SHELL"
+  if [ $# = 0 ]
+  then
+    new=1
+    set -- "$SHELL"
+  else
+    sess=$1; shift
+    if [ $# -gt 0 ]
+    then
+      echo "$cmd: extra arguments after session name \"$sess\": $*" >&2
+      badopts=1
+    fi
+  fi
 fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
-title=$sess
+echo "post post opts = $*"
 
 (
   # if new, just run up a new screen session
-  [ $new ] && exec screen -c "$rcfile" -S "$sess" -t "$title" -- "$@"
+  [ $new ] && exec screen -c "$rcfile" -- "$@"
 
   # otherwise convert $sess into session name to join
   case "$sess" in
@@ -137,7 +155,7 @@ title=$sess
   [ -n "$match" ] && exec screen -c "$rcfile" -x "$sess"
 
   # start new session
-  exec screen -c "$rcfile" -S "$sess" -t "$title" -- "$@"
+  exec screen -c "$rcfile" -- "$@"
 )
 
 [ -n "$tmprc" ] && rm "$tmprc"
