Replace scr (screen wrapper) with scrif code (screen-at-need script), merge functionality. [CVS rev 1.9]

diff --git a/scr b/scr
--- a/scr
+++ b/scr
@@ -1,56 +1,73 @@
 #!/bin/sh
 #
-# Simple wrapper for screen to list screens or attach to running session.
-#	- Cameron Simpson <cs@zip.com.au> 16apr2002
+# Attach to specified screen or make new one of specified name.
+#	- Cameron Simpson <cs@zip.com.au> 18may2002
 #
 
-cmd=`basename "$0"`
-usage="Usage:	$cmd				List sessions.
-	$cmd session-name		Join session (shared).
-	$cmd -options... [args...]]	Exec screen with supplied arguments."
+cmd=$0
+usage="Usage:
+    $cmd
+	List sessions.
+    $cmd [-N] session-name [cmd [args...]]
+	Join named session, creating it if missing.
+	-N	Force new session."
 
 # nothing? list active sessions
 [ $# = 0 ] \
     && { screen -ls \
 	 | sed -e '/^	/!d' -e 's/^	\([^	]*\).*/\1/' \
-	 | awk '{ printf("%3d %s\n",NR,$0) }'
+	 | awk '{ print NR, $0 }'	## printf("%d %s\n",NR,$0) }'
 	 exit 0
        }
 
 badopts=
-scropts=
 
-while :
-do  case $1 in
-      -[aAfilLmOqRsUvxX]|-f[na]|-ln)
-		scropts="$scropts $1" ;;
-      -[cdDerSt])
-		scropts="$scropts $1 $2"; shift ;;
-      --)	shift; break ;;
-      -?*)	echo "$cmd: unrecognised option: $1" >&2; badopts=1 ;;
-      *)	break ;;
-    esac
-    shift
-done
+new=
+[ "x$1" = x-N ] && { new=1; shift; }
 
 if [ $# = 0 ]
-then  echo "$cmd: missing screen name or number" >&2; badopts=1
-else  name=$1; shift
-      [ $# = 0 ] || { echo "$cmd: extra arguments: $*" >&2; badopts=1; }
+then
+  if [ $new ]
+  then
+    nsess=`scr|wc -l`
+    nsess2=`expr $nsess + 1`
+    sess=${shell:-`basename "$SHELL"`}$nsess2
+    set "$SHELL"
+  else
+    echo "$cmd: missing session-name" >&2
+    badopts=1
+  fi
+else
+  sess=$1; shift
+  [ $# = 0 ] && set "$SHELL"
 fi
 
 [ $badopts ] && { echo "$usage" >&2; exit 2; }
 
-case "$name" in
-    [1-9]|[1-9][0-9]|[1-9][0-9][0-9])
-	n=$name
-	name=`scr | sed -n -e "$n!d" -e 's/^ *[1-9][0-9]*  *//p'`
-	[ -n "$name" ] || { echo "$cmd: no ${n}th session; available sessions:" >&2
-			    scr >&2
-			    exit 1
-			  }
+# if new, just run up a new screen session
+[ $new ] && exec screen -S "$sess" -- "$@"
+
+# otherwise convert $sess into session name to join
+case "$sess" in
+  [1-9]|[1-9][0-9]|[1-9][0-9][0-9])
+	# numeric - pull name from listing
+	nsess=`scr | sed -n "s/^ *$sess //p"`
+	[ -n "$nsess" ] || { echo "$cmd: no screen numbered $sess" >&2
+			     exit 1
+			   }
+	# matched - join the session
+	exec screen -x "$nsess"
 	;;
+
+  # strip slashes from session name if necessary
+  */*)	sess=`echo "$sess" | tr / _` ;;
 esac
 
-set -x
-exec screen $scropts -A -e '' -h 10240 -l -d -r "$name"
+# not numeric - look up in listing
+match=`scr | sed -e "/^ *[1-9][0-9]* [1-9][0-9]*\\.$sess\$/!d" -e 's/^ *[1-9][0-9]*  *//' -e q`
+
+# match found - join it
+[ -n "$match" ] && exec screen -x "$sess"
+
+# start new session
+exec screen -S "$sess" -- "$@"
