Add -f (force - no sudo) and -F config-file options.

diff --git a/sshpf b/sshpf
--- a/sshpf
+++ b/sshpf
@@ -7,17 +7,50 @@
 : ${OPTCSS:=/opt/css}
 : ${VARRUN:=$HOME/var/run}
 
-cf=$HOME/rc/ssh/config-pf
+cf=${SSHPF_SSH_CONFIG:-$HOME/rc/ssh/config-pf}
 delay=120
+force=
+
+cmd=$0
+usage="Usage: $cmd [-f] [-F config] [targets...]
+  -f            Force. No sudo.
+  -F config     Specify ssh configuration file to use.
+                Default: \$SSHPF_SSH_CONFIG, or \$HOME/rc/ssh/config-pf
+  targets       Host clause names from config.
+                Default: \$SSHPF_DFLT"
+
+badopts=
+
+while [ $# -gt 0 ]
+do
+  case $1 in
+    -f) force=1 ;;
+    -F) cf=$2; shift ;;
+    --) shift; break ;;
+    -?*)echo "$cmd: unrecognised option: $1" >&2
+        badopts=1
+        ;;
+    *)  break ;;
+  esac
+  shift
+done
+
+[ -s "$cf" ] || { echo "$cmd: missing ssh config: $cf" >&2; badopts=1; }
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 [ $# -gt 0 ] || set -- $SSHPF_DFLT
 
-uid=`id -u` || exit 1
-if [ "x$uid" != x0 ]
+if [ -z "$force" ]
 then
-  qcmd=`shqstr "$0" ${1+"$@"}`
-  set -x
-  exec sudo env "OPTCSS=$OPTCSS" "HOME=$HOME" "VARRUN=$VARRUN" sh -c ". \"\$OPTCSS/env.sh\"; exec $qcmd"
+  # become root if not root already
+  uid=`id -u` || exit 1
+  if [ "x$uid" != x0 ]
+  then
+    qcmd=`shqstr "$0" ${1+"$@"}`
+    set -x
+    exec sudo env "OPTCSS=$OPTCSS" "HOME=$HOME" "VARRUN=$VARRUN" sh -c ". \"\$OPTCSS/env.sh\"; exec $qcmd"
+  fi
 fi
 
 pidfile=$VARRUN/sshpf.pid
