Proper usage message. Support multiple PDF files and URLs. Get /opt/pdftohtml/bin/pdftohtml to avoid obsolete script in /opt/script. [CVS rev 1.2]

diff --git a/unpdf b/unpdf
--- a/unpdf
+++ b/unpdf
@@ -5,15 +5,39 @@
 #
 
 cmd=`basename "$0"`
-tmpdir=`mkdirn "/tmp/$cmd"` || exit 1
+usage="Usage: $cmd {file|URL|-}..."
 
-xit=1
-trap 'rm -rf "$tmpdir"; exit $xit' 0 1 3 15
+tmpf=${TMPDIR:-/tmp}/$cmd$$.pdf
 
-cat ${1+"$@"} >"$tmpdir/it.pdf" || exit 1
-
-pdftohtml -stdout "$tmpdir/it.pdf" \
-| sed -e 's/^ *<br>$/<P>/' -e 's/ *<br>$//' \
-| unhtml
+[ $# = 0 ] && { echo "$cmd: missing arguments" >&2
+		echo "$usage" >&2
+		exit 2
+	      }
 
 xit=0
+
+first=1
+for arg
+do
+  case "$arg" in
+    -)		cat ;;
+    http://*)	wcat "$arg" ;;
+    /*)		cat "$arg" ;;
+    *)		cat "./$arg" ;;
+  esac >"$tmpf" || { xit=1; continue; }
+
+  # separators
+  if [ $first ]
+  then  first=
+  else  echo '<HR>\n'
+  fi
+
+  /opt/pdftohtml/bin/pdftohtml -stdout -noframes "$tmpf" \
+  || { xit=1; continue; }
+done \
+| sed -e 's/^ *<br>$/<P>/' \
+| unhtml
+
+trap 'rm "$tmpf"; exit $xit' 0 1 3 15
+
+exit $xit
