opendir: improve command line sanity checking, reject nondirectories

diff --git a/bin-cs/opendir b/bin-cs/opendir
--- a/bin-cs/opendir
+++ b/bin-cs/opendir
@@ -6,13 +6,32 @@
 
 set -ue
 
+: ${OS:=`uname -s`}
+
 cmd=$0
 usage="Usage: $cmd dirpath"
 
-[ $# = 1 ] || { echo "$usage" >&2; exit 2; }
-dirpath=$1
+badopts=
 
-: ${OS:=`uname -s`}
+if [ $# = 0 ]
+then
+  echo "$cmd: missing dirpath" >&2
+  badopts=1
+else
+  dirpath=$1
+  shift
+  [ -d "$dirpath" ] || {
+    echo "$cmd: not a directory: $dirpath" >&2
+    badopts=1
+  }
+fi
+
+[ $# = 0 ] || {
+  echo "$cmd: extra arguments after dirpath: $*" >&2
+  badopts=1
+}
+
+[ $badopts ] && { echo "$usage" >&2; exit 2; }
 
 case "$OS" in
   [Dd]arwin)
