push-tvwiz: sanity check the target

diff --git a/bin-cs/push-tvwiz b/bin-cs/push-tvwiz
--- a/bin-cs/push-tvwiz
+++ b/bin-cs/push-tvwiz
@@ -31,6 +31,18 @@ do
   shift
 done
 
+if [ -z "$target" ]
+then
+  echo "$cmd: missing -d target" >&2
+  badopts=1
+else
+  if [ ! -d "$target/." ]
+  then
+    echo "$cmd: target is not a directory: $target" >&2
+    badopts=1
+  fi
+fi
+
 if [ $# = 0 ]
 then
   echo "$cmd: missing sources" >&2
