selftest: tweak syntax state pathnames, add state for unittests

diff --git a/bin-cs/selftest b/bin-cs/selftest
--- a/bin-cs/selftest
+++ b/bin-cs/selftest
@@ -62,9 +62,9 @@ test_python()
     { xit=0 
       while read -r py 
       do 
-        pyc_state=state/pyc/${py}c
+        pyc_state=state/pyc/$py
         if [ "$pyc_state" -nt "$py" ]
-        then  $vecho "SKIP $py - $pyc_state newer"
+        then  $vecho "SKIP syntax $py - newer $pyc_state"
         else
           rm -f -- "$pyc_state"
           if $trace pfx "$py" env-dev python -tt -m py_compile "$py"
@@ -83,12 +83,20 @@ test_python()
     { xit=0 
       while read -r py 
       do 
-        unitest=`sed -n '${/^ *unittest\.main/p;}' "$py"` 
-        [ -n "$unitest" ] || continue 
-        pym=`expr "x$py" : "x$pylibdir"'/\(.*\).py' | tr / .` 
-        if $trace env-dev -x python -tt -B -m "$pym"
-        then  $vecho "OK unit test $py"
-        else  echo "FAIL: unitest $py" >&2; return 1
+        pyu_state=state/pyu/$py
+        if [ "$pyu_state" -nt "$py" ]
+        then  $vecho "SKIP unittest $py - newer $pyu_state"
+        else
+          d=`dirname "$pyu_state"`; [ -d "$d" ] || mkdir -p "$d"
+          >>"$pyu_state"
+          unitest=`sed -n '${/^ *unittest\.main/p;}' "$py"` 
+          [ -n "$unitest" ] || continue 
+          rm -f "$pyu_state"
+          pym=`expr "x$py" : "x$pylibdir"'/\(.*\).py' | tr / .` 
+          if $trace env-dev -x python -tt -B -m "$pym"
+          then  $vecho "OK unit test $py"; >>"$pyu_state"
+          else  echo "FAIL: unitest $py" >&2; return 1
+          fi
         fi
       done 
       return $xit 
