updcss: turn off _man, buggy

diff --git a/bin-cs/updcss b/bin-cs/updcss
--- a/bin-cs/updcss
+++ b/bin-cs/updcss
@@ -101,7 +101,7 @@ hg-apply-manifest-dates -r "$rev" "$dstdir"
   echo man...
   mkdir -p "$optcss/man"
   rsync -aH "$optcss/man/" man/
-  myke "MANDIR=$dstdir/man" _man || echo myke _man fails, ignoring...
+  echo SKIP myke "MANDIR=$dstdir/man" _man || echo myke _man fails, ignoring...
 )
 
 echo CHANGELOG.txt...
